- name: Deploy Redis Pod
  hosts: localhost
  tasks:
    - name: Set up Kubeconfig path
      ansible.builtin.set_fact:
        kubeconfig_path: "C:/Users/jy811/.kube/config"

    - name: Copy Kubeconfig to Remote
      local_action:
        module: ansible.builtin.copy
        src: "{{ kubeconfig_path }}"
        dest: /tmp/kubeconfig

    - name: Create Redis Pod
      kubernetes.core.k8s:
        kubeconfig: /tmp/kubeconfig
        state: present
        definition:
          apiVersion: v1
          kind: Pod
          metadata:
            name: redis
            namespace: default
            labels:
              app: redis
          spec:
            containers:
            - name: redis
              image: docker.io/redis:latest
              ports:
              - containerPort: 6379
