---
- name: Deploy Ubuntu Pod in Minikube
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create Ubuntu Pod definition
      copy:
        content: |
          apiVersion: v1
          kind: Pod
          metadata:
            name: ubuntu-pod
            namespace: default
          spec:
            containers:
              - name: ubuntu
                image: ubuntu:latest
                command: ["sleep", "infinity"]
        dest: /tmp/ubuntu-pod.yml

    - name: Apply Pod definition to Minikube
      command: kubectl apply -f /tmp/ubuntu-pod.yml
      register: kubectl_output

    - name: Output result
      debug:
        var: kubectl_output.stdout
