- name: Deploy Redis Pod in Minikube
  hosts: localhost
  tasks:
    - name: Create Redis Pod
      kubernetes.core.k8s:
        kubeconfig: /tmp/kubeconfig
        state: present
        definition:
          apiVersion: v1
          kind: Pod
          metadata:
            name: redis
            namespace: default
            labels:
              app: redis
          spec:
            containers:
            - name: redis
              image: docker.io/redis:latest
              ports:
              - containerPort: 6379
      delegate_to: localhost
